%.html: header %.page footer
	cat $^ > $@

default: *.html

# target: dependencies
#    instructions

# sam.html: header sam.page footer
#    cat header sam.page footer > sam.html
# nico.html: header nico.page footer
#    cat header nico.page footer > nico.html

# $^ is "the dependencies"
# sam.html: header sam.page footer
#    cat $^ > sam.html

# $@ is "the target"
# sam.html: header sam.page footer
#    cat $^ > $@
# nico.html: header nico.page footer
#    cat $^ > $@

# % is a wildcard in Make
# %.html: header %.page footer
#    cat $^ > $@
